"""Scene list for "Why You Can't Tickle Yourself".

Each beat is (narration, scene). The narration is the exact script text for
that beat; timestamps are computed from cumulative word counts in build.py.
"""

BEATS = [
    ("Try to tickle yourself. Actually do it.",
     "A stick figure sitting on the floor looking at the viewer, pointing at its own bare foot with a curious face. A big question mark floats above its head."),
    ("Run your fingers along the bottom of your foot,",
     "A stick figure holding up one bare foot and wiggling its fingers along the sole. Small wobbly motion lines near the fingers."),
    ("or the side of your ribs, the spot that makes you squirm when someone else touches it.",
     "Left side: a stick figure squirming and laughing while a second stick figure pokes its ribs, with squiggly laugh lines. Right side: the same stick figure alone touching its own ribs."),
    ("Nothing.",
     "A single stick figure touching its own ribs with a completely flat, bored face (straight-line mouth). Plenty of empty white space around it."),
    ("You can feel your fingers. You can feel exactly where they are and how light they are.",
     "Close-up of a big simple hand with wiggling fingers touching a patch of skin. A small arrow points to the fingertips with a little feather drawn next to it to show 'light'."),
    ("It's the same touch, on the same skin, in the same place.",
     "Two identical panels side by side: a hand touching a foot. Between them a big wobbly equals sign '='."),
    ("But it doesn't tickle, and no matter how hard you try, it never will.",
     "A sweaty stick figure frantically tickling its own foot with both hands, lots of motion lines, while its face stays totally unamused. Sweat drops fly off its head."),
    ("That seems like a silly little fact about being human. It isn't.",
     "A stick figure shrugging next to a small silly doodle of a foot. A big red X is scribbled over the word 'SILLY'."),
    ("It's one of the clearest windows we have into how your brain decides what's real, what's you, and what's someone else.",
     "A big pink blob brain drawn inside a square window frame. Inside the window: a small stick figure labeled 'ME' and another labeled 'NOT ME' with an arrow between them."),
    ("When that system breaks, people start hearing voices.",
     "A worried stick figure holding its head. The brain above it has a crack drawn through it. Small speech bubbles with scribbles float around its head."),
    ("People have been stuck on this question for a long time.",
     "A stick figure standing on a very long timeline arrow drawn across the whole frame, scratching its head. A huge question mark sits at the start of the line."),
    ("A collection of scientific puzzles attributed to Aristotle, written more than 2,000 years ago, asks it directly:",
     "A stick figure with a bushy beard and a toga (simple triangle robe) holding an old paper scroll. A wobbly Greek column stands next to him. Small text '2000+ YEARS AGO' at the top."),
    ("why can't a person tickle himself?",
     "The bearded toga stick figure tickling his own foot with a confused face. A big speech bubble with a question mark."),
    ("In 1872, Charles Darwin noticed something important about it.",
     "A stick figure with a big bald head, long white beard and a simple coat, looking thoughtful with a finger on his chin. A small sign reads '1872'."),
    ("He wrote that for tickling to work, the person being tickled can't know exactly where the touch is going to land.",
     "A blindfolded stick figure. A hand is coming toward it with a dotted wiggly path and question marks along the path showing it's unpredictable."),
    ("A child, he pointed out, can hardly tickle itself at all.",
     "A small stick figure child with a round head and tiny body trying to tickle its own tummy, looking puzzled. The bearded Darwin figure watches from the side nodding."),
    ("He was close. But it would take another century, and a machine, to work out what was really going on.",
     "A calendar with pages flying off it on the left, and on the right a clunky boxy machine with a lever and gears, with a question mark over it."),
    ("In 1971, three researchers at Oxford named Lawrence Weiskrantz, John Elliott and Christine Darlington built a tickling device.",
     "Three stick figures in lab coats (two men, one woman with long hair) standing proudly next to a clunky homemade machine. A sign above reads '1971'."),
    ("It was a lever connected to a soft tip that brushed the sole of your foot.",
     "A simple side-view diagram: a bare foot resting on a box, a long lever with a fuzzy soft tip touching the bottom of the foot. Arrows show the lever going back and forth."),
    ("Sometimes the experimenter worked the lever.",
     "A lab coat stick figure pushing the lever while a volunteer stick figure sits with its foot on the machine, giggling with squiggly laugh lines."),
    ("Sometimes the volunteer did it themselves.",
     "The volunteer stick figure pushing the lever on its own foot, looking bored with a flat mouth. The lab coat figure watches holding a clipboard."),
    ("When someone else moved it, people rated it as ticklish.",
     "A big simple bar chart with one very tall bar labeled 'OTHER'. Next to it a laughing stick figure face."),
    ("When they moved it themselves, the feeling dropped away.",
     "The same bar chart: tall bar 'OTHER' next to a very short bar labeled 'SELF'. A down arrow points at the short bar. A bored stick figure face next to it."),
    ("Then came the strange part.",
     "A stick figure scientist with wide eyes and raised eyebrows leaning in closely, with a big exclamation mark above its head."),
    ("When the volunteer just rested their hand on the lever while the experimenter moved it, so their hand went along for the ride without making the movement,",
     "The volunteer's hand resting limp on the lever while the lab coat stick figure's hand pushes it. The volunteer's hand gets dragged along, drawn with little dotted motion lines. The volunteer looks relaxed."),
    ("it landed somewhere in between.",
     "A bar chart with three bars: tall 'OTHER', medium 'HAND ALONG', short 'SELF'. An arrow points at the middle bar."),
    ("So it wasn't about whose hand was touching you. It was about who decided to move.",
     "A stick figure with a thought bubble containing a lightbulb and the word 'DECIDE'. An arrow goes from the thought bubble down to its hand."),
    ("To understand why, you have to know about a message your brain sends every time you do anything.",
     "A big blob brain holding a little envelope with a wing on it, the envelope flying toward a stick figure's arm."),
    ("Try this. Close one eye, and with your fingertip, very gently press on the side of your other eyelid. Just a light nudge.",
     "Large close-up of a simple stick figure face with one eye closed (a line) and a finger gently pressing the side of the other eye. A small arrow shows the gentle push."),
    ("The world moves. The whole room jumps.",
     "A simple room with a table, a lamp and a window, all drawn doubled and tilted with shaky motion lines, as if the whole room jumped. The stick figure looks startled."),
    ("Now move your eye normally. Look left, then right.",
     "A big stick figure face with both eyes looking to the left, and next to it the same face with eyes looking right. Curved arrows between them."),
    ("The room stays perfectly still.",
     "The same simple room with table, lamp and window, perfectly straight and calm. The stick figure stands in the middle with a small smile."),
    ("Your eye moved both times, and the image on the back of it shifted both times.",
     "A big round eyeball drawn from the side, with a tiny upside-down picture of a house on the back of it, and arrows showing the tiny picture sliding."),
    ("But only one of those made the world lurch.",
     "Two panels: left panel a finger poking an eye with a shaky room and a sad face; right panel a normally moving eye with a calm room and a happy face. Left has a red X-ish shake symbol, right has a check mark."),
    ("The difference is that when you move your eye on purpose, your brain sends a copy of the command to itself,",
     "A blob brain sending one arrow down to the eye labeled 'MOVE', and a second arrow looping back into itself carrying a little paper copy."),
    ("a note that says I'm about to move, so expect everything to shift by this much.",
     "A sticky note stuck on the brain that reads 'MOVING! EXPECT SHIFT' in wobbly handwriting, with a small arrow and a ruler doodle."),
    ("When the shift arrives, it matches the prediction and gets cancelled out. You never notice.",
     "Two identical puzzle pieces fitting together, one labeled 'PREDICTION' and one labeled 'SHIFT'. Above them a big cancel sign (circle with a line through it). A calm stick figure beside it."),
    ("When you push your eye with your finger, no note was sent.",
     "A finger poking an eye. Next to the brain, an empty sticky note spot with a big question mark and an empty mailbox."),
    ("The movement arrives unannounced, so your brain assumes it wasn't you. It must have been the world.",
     "A blob brain with alarmed eyes pointing at a spinning planet Earth doodle, with a speech bubble saying 'NOT ME! THE WORLD!'"),
    ("Scientists call that internal note an efference copy.",
     "A chalkboard with the words 'EFFERENCE COPY' written in big shaky letters and a doodle of a sticky note. A stick figure teacher points at it with a stick."),
    ("Two German researchers, Erich von Holst and Horst Mittelstaedt, described it in 1950,",
     "Two stick figure scientists in lab coats shaking hands, holding a paper. A small sign reads '1950'."),
    ("and the same year an American named Roger Sperry landed on the same idea independently.",
     "A third stick figure scientist on the other side of the frame, far away, with a lightbulb above his head and the same paper. A dashed line connects him to the two other scientists."),
    ("Nearly everything with a nervous system seems to have some version of it.",
     "A row of simple doodled animals: a fish, a bird, a cat, a bug and a stick figure human, each with a tiny sticky note above its head."),
    ("A male cricket chirps at around 100 decibels, loud enough to damage its own hearing.",
     "A big simple green cricket with its mouth open, huge jagged sound waves blasting out. A small sign reads '100 dB'. Tiny ears shown with warning marks."),
    ("It doesn't go deaf, because every time it chirps, its nervous system sends a signal that quiets its own ears at exactly that moment.",
     "The cricket chirping while a little arrow from its tiny brain goes to its ears, where a pair of small earmuffs appears."),
    ("In 2006, researchers Berthold Hedwig and James Poulet recorded that signal firing in perfect rhythm with the chirp.",
     "Two stick figure scientists looking at a computer screen showing two wobbly lines of spikes lined up perfectly. A small cricket sits on the desk. A sign reads '2006'."),
    ("The cricket is silencing itself so it can still hear everything else.",
     "The cricket wearing earmuffs only on its own chirp, while it happily hears a small bird singing nearby with music notes floating to it."),
    ("You do the same thing with touch.",
     "A stick figure human standing next to the cricket, both giving a thumbs up, the human pointing at its own hand."),
    ("When you move your fingers toward your ribs, your brain already knows what's coming: the timing, the pressure, the exact path.",
     "A hand moving toward a stick figure's ribs along a dotted path. Above, the brain holds a checklist: 'TIME ✓ PRESSURE ✓ PATH ✓'."),
    ("The prediction arrives before the sensation does, and the sensation gets turned down.",
     "A race track with two runners: a stick figure labeled 'PREDICTION' crossing the finish line first and a slower one labeled 'FEELING' behind. A big volume knob next to it turned all the way down."),
    ("Tickling is what happens when touch arrives that your brain didn't predict.",
     "A brain with surprised wide eyes being poked by a hand that comes out of nowhere, with a big 'SURPRISE!' in wobbly letters."),
    ("It's the feeling of something else touching you.",
     "A stick figure laughing and squirming while a mysterious hand from outside the frame tickles its side."),
    ("You can't surprise yourself, so you can't tickle yourself.",
     "A stick figure jumping out from behind a box yelling 'BOO!' at... itself, looking in a mirror, with a flat bored face in the reflection."),
    ("In the late 1990s, a team in London set out to prove it.",
     "A very simple London skyline with Big Ben doodled in wobbly lines. A small building labeled 'LAB'. A sign reads 'LATE 1990s'."),
    ("Sarah-Jayne Blakemore, Daniel Wolpert and Chris Frith built a setup with two robot arms.",
     "Three stick figure scientists (one woman with long hair, two men) standing next to two clunky robot arms made of boxes and tubes."),
    ("The volunteer moved one arm with their left hand.",
     "A volunteer stick figure moving a joystick on the first robot arm with its left hand. An arrow shows the direction of movement."),
    ("That movement was sent to a second robot, which stroked a piece of soft foam across the palm of their right hand.",
     "A wire goes from the first robot arm to a second robot arm, which holds a fluffy yellow square of foam brushing across the volunteer's open right palm."),
    ("You're tickling yourself, just through a robot. And like always, it barely tickled.",
     "The volunteer operating the robots with a bored flat face. A small tickle meter next to it with the needle almost at zero."),
    ("Then the researchers started adding delays.",
     "A scientist stick figure holding a big stopwatch and turning a knob labeled 'DELAY' on the robot."),
    ("A tenth of a second between your movement and the touch. Then two tenths. Then three.",
     "Three small panels in a row showing stopwatches labeled '0.1s', '0.2s', '0.3s', each with a slightly more giggly stick figure face below."),
    ("The longer the delay, the more it tickled.",
     "A simple line graph going up from bottom left to top right, x axis 'DELAY' and y axis 'TICKLE'. At the top of the line a laughing stick figure face."),
    ("They tried something else. Instead of delaying the touch, they rotated it, so when you moved the stick one direction, the foam moved at an angle.",
     "The joystick moving straight up with an arrow, and the foam on the palm moving diagonally with a tilted arrow. A curved angle mark between the arrows."),
    ("The bigger the angle, the more it tickled.",
     "Three angle arcs growing bigger from left to right, each with a stick figure face getting more and more giggly, the last one laughing hard."),
    ("Nothing about the touch itself had changed, and the volunteer was still the one causing it.",
     "The volunteer pointing at itself with a label 'STILL ME', next to the foam on the palm, which looks exactly the same as before."),
    ("All the researchers did was make the touch slightly different from what the brain predicted.",
     "Two overlapping dotted paths, one labeled 'PREDICTED' and one labeled 'ACTUAL', slightly off from each other. A magnifying glass shows the small gap."),
    ("A few hundred milliseconds, a few degrees off, and suddenly it felt like someone else.",
     "The volunteer laughing, with a ghostly dotted-outline stick figure appearing next to it as if a stranger was tickling. A small clock and angle icon."),
    ("When they scanned people's brains during self-touch, they found the areas that process touch were measurably quieter when the touch was self-made.",
     "A stick figure lying in a big donut-shaped brain scanner. A screen shows two brains: one with a big bright spot labeled 'OTHER', one with a small dim spot labeled 'SELF'."),
    ("The cerebellum, a region at the back of the brain that helps predict the results of your movements,",
     "A big side-view blob brain with the small wrinkly bump at the back colored in and labeled 'CEREBELLUM' with an arrow."),
    ("seemed to be sending the signal to turn it down.",
     "The cerebellum drawn with a tiny arm reaching over and turning down a volume knob on the rest of the brain."),
    ("So your brain isn't just feeling the world. It's constantly subtracting you from it,",
     "A big math equation: 'WORLD' (with a tree and a sun) minus 'YOU' (a stick figure) equals a small pile. Written in wobbly handwriting."),
    ("filtering out every sensation you cause so that whatever's left over, whatever it didn't see coming, stands out.",
     "A kitchen strainer/sieve with many small grey dots labeled 'YOU' falling through, and one big bright red dot left in the strainer labeled 'SURPRISE'."),
    ("That leftover is how you know something else is there.",
     "A stick figure noticing a single footprint or a small mysterious shadow next to it, pointing with a surprised face."),
    ("That filter has a cost, and you've probably felt it.",
     "A price tag hanging off the kitchen strainer that reads 'COST'. A stick figure looks at it worried."),
    ("In 2003, a team in London, including Wolpert and Frith, sat pairs of people across from each other.",
     "Two stick figures sitting across a small table from each other. Two scientists stand behind with clipboards. A sign reads '2003'."),
    ("Each person had a finger resting under a small lever.",
     "Close-up of a simple finger lying flat under a small lever bar on the table."),
    ("Person one pressed down on the other's finger. Person two was told to press back with exactly the same force.",
     "Stick figure 1 pushing down on a lever with a small arrow. Stick figure 2 feeling it, then pressing back with a small arrow. Labels '1' and '2' above their heads."),
    ("Then person one was told to match that, and so on, back and forth.",
     "The two stick figures across the table with a big circular back-and-forth arrow between them."),
    ("Everyone was trying to be fair. Everyone was trying to match.",
     "Both stick figures smiling politely, each holding a small balance scale."),
    ("But the force went up about 38% with every turn.",
     "A staircase of arrows going up, each step labeled '+38%'. The two stick figures look slightly annoyed."),
    ("Within a few rounds they were pressing down roughly 20 times harder than where they started.",
     "The two stick figures now red-faced and straining, pushing with huge thick arrows. A small sign reads 'x20'. The table is slightly bending."),
    ("The reason is the same filter. When you press on someone else, your brain predicts your own force and turns down how it feels to you.",
     "A stick figure pushing a lever while its brain turns a volume knob down on its own push arrow, making the arrow look small to it."),
    ("So your own push always feels softer than it really is, and theirs always feels harder.",
     "Two arrows: one small labeled 'MY PUSH (FEELS)' and one big labeled 'YOUR PUSH (FEELS)', side by side for comparison."),
    ("Each person, honestly trying to match, hits back harder than they were hit.",
     "Two stick figures each with a halo above their heads (honest), but pushing back with bigger and bigger arrows."),
    ("The researchers titled their paper Two Eyes for an Eye.",
     "A simple paper document with the title 'TWO EYES FOR AN EYE' in wobbly letters and a doodle of two eyeballs on the cover."),
    ("It's a pretty good explanation of every argument you've had that got worse than it needed to be.",
     "Two stick figures arguing with angry eyebrows, with growing speech bubbles full of scribbles and a small storm cloud above."),
    ("\"I only pushed back as hard as you pushed me.\" Both of you believe it, and both of you are wrong.",
     "Two stick figures pointing at each other, both saying 'YOU STARTED IT!' in speech bubbles. A big red X over both of them."),
    ("It gets darker from here.",
     "The same white background but a big dark scribbled storm cloud and a small worried stick figure walking toward it."),
    ("If your brain labels everything you do as me and everything else as not me,",
     "A brain holding a label gun, sticking a 'ME' sticker on a stick figure's own hand and a 'NOT ME' sticker on a tree."),
    ("what happens when the label stops working?",
     "A broken label gun with springs popping out and blank labels falling on the floor. A confused stick figure with a question mark."),
    ("Chris Frith, one of the researchers behind the robot study, spent much of his career on schizophrenia.",
     "A stick figure scientist with glasses at a desk piled high with papers, the top folder reads 'SCHIZOPHRENIA'."),
    ("He noticed something about two of its most common symptoms.",
     "The scientist holding a magnifying glass over two circles labeled '1' and '2'."),
    ("Many people with schizophrenia hear voices,",
     "A stick figure sitting alone looking uneasy, with several small speech bubbles containing squiggles floating around its head, and no one else around."),
    ("and many also report something called passivity experiences, a feeling that their movements are being controlled by an outside force,",
     "A stick figure drawn like a puppet, with simple strings attached to its arms going up to the top of the frame. It looks confused."),
    ("that someone else is moving their arm.",
     "A stick figure staring at its own arm as it lifts by itself. A dotted ghost hand is pulling the arm up. A question mark above."),
    ("Frith wondered if both of those could come from the same broken tag.",
     "The scientist with a thought bubble showing a torn 'ME' tag with two arrows coming off it, one to a speech bubble and one to a puppet string."),
    ("What if your own actions arrived without the note that says this was you?",
     "A hand moving, with an empty envelope floating next to it and a big question mark. The sticky note 'THIS WAS YOU' is crossed out."),
    ("In 2000, Blakemore and Frith ran the tickle test on people with schizophrenia.",
     "The two robot arms and foam set up again. A patient stick figure sits at the controls. Two scientists watch. A sign reads '2000'."),
    ("Healthy volunteers rated self-touch as much less ticklish than touch from the experimenter.",
     "A bar chart labeled 'HEALTHY' with a tall bar 'OTHER' and a short bar 'SELF'."),
    ("But the patients who heard voices, or felt their bodies being controlled, rated both about the same.",
     "A second bar chart labeled 'PATIENTS' with two bars of the same height, 'OTHER' and 'SELF', and an equals sign between them."),
    ("They could tickle themselves.",
     "A stick figure tickling its own foot and actually laughing, with squiggly laugh lines. A surprised scientist drops a clipboard in the background."),
    ("To their brains, their own touch felt just as foreign as a stranger's.",
     "The stick figure's own hand drawn wearing a disguise: a fake mustache and a little hat, labeled 'STRANGER?'."),
    ("Now think about what that means for your inner voice.",
     "A stick figure with a small speech bubble inside its own head, the bubble drawn inside the head outline."),
    ("You're talking to yourself right now, reading these words in your head.",
     "A stick figure reading a book, with a small speech bubble inside its head repeating the words 'blah blah'."),
    ("There's evidence the brain uses a similar prediction to mark that voice as yours, quieting its response to your own speech the way it quiets your own touch.",
     "A brain stamping a 'ME' stamp onto a speech bubble, and a volume knob next to the bubble turned down."),
    ("If that mark fails, your own thoughts could arrive sounding like they came from somewhere else.",
     "A speech bubble leaving a stick figure's head, looping around outside, and coming back in its ear from the other side. The stick figure looks confused."),
    ("Not imagined voices. Your voice, with the \"me\" label torn off.",
     "A speech bubble with a 'ME' label hanging half torn off it. The stick figure holds its head."),
    ("The line between you and not-you isn't something you're born knowing.",
     "A baby stick figure in a diaper with a question mark, and a wobbly line drawn on the ground between the baby and the rest of the world."),
    ("It's something your brain calculates, moment by moment, out of predictions.",
     "A brain wearing glasses sitting at a desk with an old calculator, a pile of papers labeled 'PREDICTIONS'."),
    ("Most of the time it gets it right, so perfectly you never think about it.",
     "A stick figure happily walking along the street, whistling, with a big green checkmark above its head."),
    ("But it's a calculation, and calculations can go wrong.",
     "The calculator with a cracked screen showing 'ERROR' and a tiny puff of smoke. The brain looks worried."),
    ("That brings us back to the tickle.",
     "A big fluffy feather drawn in the center of the frame, with a small curved arrow circling back to it."),
    ("There's a reason tickling seems to exist at all.",
     "A stick figure standing in front of a big feather, thinking with a hand on its chin and a question mark."),
    ("It shows up almost entirely between people: parents and babies, siblings, friends.",
     "Three small scenes in a row: a parent tickling a baby, two sibling kids tickling each other, two friends laughing. Everyone laughing with squiggly lines."),
    ("In the late 1990s, the neuroscientist Jaak Panksepp found that rats make ultrasonic chirps when you tickle them,",
     "A scientist stick figure with a mustache gently tickling a small grey rat lying on its back in his hand. A sign reads 'LATE 1990s'."),
    ("a kind of laughter too high for us to hear,",
     "The rat laughing with tiny zig-zag sound waves going way up high, and the scientist holding a hand to his ear, hearing nothing."),
    ("and they'd chase a researcher's hand to get more.",
     "A happy rat running after a scientist's hand across a table, with little motion lines and hearts."),
    ("It's one of the first forms of play there is.",
     "A baby stick figure and a small rat both laughing next to a pile of simple toys like a ball and a block."),
    ("Tickling might be the earliest way a brain learns that there's someone else out there.",
     "A baby stick figure looking up at a parent stick figure, with a small lightbulb above the baby's head and the words 'SOMEONE ELSE!'."),
    ("A touch you didn't predict, from a person you can't control, that makes you laugh anyway.",
     "A parent tickling a giggling baby, both smiling big. Small hearts and laugh squiggles float around them."),
    ("So try it one more time. Your fingers on your ribs.",
     "The same stick figure from the start of the video touching its own ribs, looking at the viewer."),
    ("You feel them, and your brain feels them coming, cancels them out",
     "The brain above the stick figure holding a big eraser, rubbing out a dotted arrow coming toward the ribs."),
    ("and quietly signs its name at the bottom: this was you.",
     "A paper document with a pen signing at the bottom in wobbly handwriting 'this was you'. The brain holds the pen."),
    ("That's why it doesn't work.",
     "The stick figure shrugging with a flat mouth, hand still on its ribs, a small 'meh' next to it."),
    ("Out of every sensation you'll ever have, the tickle is the one that needs someone else to be there.",
     "Two stick figures side by side, one tickling the other, both laughing happily. A big wobbly heart drawn between them."),
]

# Beats that end a paragraph in the script (1-based), for paragraph pauses.
PARAGRAPH_ENDS = {
    3, 4, 7, 10, 16, 17, 21, 26, 27, 28, 29, 30, 31, 32, 37, 39, 43, 47, 50,
    53, 57, 58, 60, 61, 63, 66, 69, 72, 73, 77, 80, 83, 86, 87, 89, 94, 96,
    99, 100, 101, 106, 110, 111, 117, 119, 122, 124,
}

# Extra seconds where the narrator waits for the viewer to try something.
VIEWER_PAUSES = {
    1: 1.5,    # "Actually do it."
    29: 2.0,   # pressing on the eyelid
    31: 1.5,   # looking left, then right
    120: 1.2,  # "Your fingers on your ribs."
}
