"""Scene list for "How Sneako Made Enemies With Everyone".

Each beat is (narration, scene). Real people appear only as plain stick
figures with a name label. Timestamps are computed in build.py.
"""

BEATS = [
    ("Sneako has been banned from YouTube, Twitch, Kick and TikTok.",
     "A stick figure in a backwards cap labeled 'SNEAKO' standing in front of four closed doors labeled 'YOUTUBE', 'TWITCH', 'KICK' and 'TIKTOK', each door with a big red 'BANNED' stamp."),
    ("That used to be the craziest thing about him.",
     "A stick figure in a backwards cap labeled 'SNEAKO' shrugging next to a messy pile of red 'BANNED' stamps."),
    ("In 2026, he got banned from an entire country.",
     "A huge blob-shaped country on a simple map with a giant red 'BANNED' stamp across it. A tiny stick figure in a backwards cap stands outside a fence. A sign reads '2026'."),
    ("The richest man alive has publicly said he should be deported.",
     "A stick figure wearing a tiny gold crown, labeled 'RICHEST MAN', sitting on a pile of gold coins and pointing toward a stick figure in a backwards cap labeled 'SNEAKO'. A speech bubble reads 'SEND HIM AWAY'."),
    ("His former best friend is accusing him of something from a prison cell.",
     "A bald stick figure behind jail bars pointing angrily through the bars with a speech bubble containing '!!!'. Outside, a stick figure in a backwards cap looks confused."),
    ("Some of the loudest people on the right want him gone, and so do people on the left.",
     "A stick figure in a backwards cap stands in the middle. A small crowd on the left holds a sign 'LEFT' and a small crowd on the right holds a sign 'RIGHT', and both crowds point at him with megaphones."),
    ("This is how one streamer managed to make enemies with almost everyone in a single year.",
     "A stick figure in a backwards cap holding a phone on a selfie stick, surrounded on all sides by many angry stick figures with frowns. A small calendar reads '2026'."),
    ("Let's start in April.",
     "A big wobbly calendar page that reads 'APRIL' in the middle of the frame."),
    ("Sneako is livestreaming in New York, walking down the street looking at his phone.",
     "A stick figure in a backwards cap walking down a city street with simple box skyscrapers, looking at a phone on a selfie stick. A red dot with 'LIVE' next to the phone."),
    ("A man walks up and punches him in the face, then drags him to the ground, all on his own stream.",
     "Cartoon slapstick: another stick figure swings a fist at a stick figure in a backwards cap, with a big yellow comic 'POW!' star. The phone on the ground still shows a red 'LIVE' dot. No blood."),
    ("Sneako comes back online about an hour later, chipped tooth, saying he's fine.",
     "A phone screen showing a stick figure in a backwards cap smiling with one tooth missing and giving a thumbs up. A small clock and the words '1 HOUR LATER'."),
    ("For most streamers, getting attacked live on camera would be the story of the year.",
     "A big gold trophy labeled 'STORY OF THE YEAR', with a few stick figure streamers holding phones staring at it."),
    ("For Sneako, it was April.",
     "A stick figure in a backwards cap shrugging next to a tiny calendar page reading 'APRIL', with a tall stack of more calendar pages behind it."),
    ("Because in May, he flew to Australia.",
     "A small airplane flying along a dotted line toward a simple map of Australia with a kangaroo doodle on it. A calendar page reads 'MAY'."),
    ("He had a valid visa.",
     "A stick figure in a backwards cap proudly holding up a passport with a green check mark and the word 'VISA'."),
    ("Then the Australian government cancelled it and kicked him out, citing antisemitic and racist content.",
     "A stick figure official in a uniform stamping a big red 'CANCELLED' over a visa paper, and pointing a stick figure in a backwards cap toward an airplane with an 'EXIT' sign."),
    ("And it wasn't a temporary ban.",
     "A simple clock with a big red X over it, and the word 'TEMPORARY' crossed out."),
    ("Under a law Australia had just updated, he can never apply for a visa there again. For life.",
     "A simple map of Australia wrapped in chains with a giant padlock, and a sign that reads 'BANNED FOR LIFE'."),
    ("Then came the World Cup.",
     "A big black and white soccer ball next to a shiny gold cup trophy, with little sparkle lines."),
    ("Egypt beats Australia, and Sneako is out in the streets of New York celebrating on stream.",
     "A scoreboard reading 'EGYPT WINS'. Below it, a stick figure in a backwards cap jumping and cheering on a city street, holding a phone on a selfie stick with a red 'LIVE' dot."),
    ("He declares the city an \"Islamic Republic,\" and the clip explodes, tens of millions of views across platforms.",
     "A phone screen showing a video play button, exploding with stars and motion lines, and a big view counter reading '10,000,000+ VIEWS'."),
    ("Alex Jones reposts it and demands the Trump administration deport him.",
     "A red-faced stick figure with a name tag 'ALEX JONES' shouting into a megaphone, holding a phone that shows a shared video. A speech bubble reads 'SEND HIM OUT!'"),
    ("Elon Musk replies with one word: yes.",
     "A phone screen showing a reply from a stick figure labeled 'ELON MUSK' with one big word: 'YES'."),
    ("Here's the problem.",
     "A stick figure raising one finger with a serious face, next to a big wobbly 'BUT...'."),
    ("Sneako was born in New York. He's an American citizen.",
     "A paper birth certificate reading 'BORN: NEW YORK' next to a blue passport reading 'CITIZEN'. A stick figure in a backwards cap stands beside them."),
    ("You can't deport a citizen.",
     "A red 'DEPORT' stamp bouncing off a big shield labeled 'CITIZEN', with little 'BOING' motion lines."),
    ("Sneako knows this, and he doesn't back down.",
     "A stick figure in a backwards cap with arms crossed and a smug smirk, standing firm with feet planted."),
    ("He tells Musk, who was born in South Africa, to go back to Africa.",
     "A stick figure in a backwards cap labeled 'SNEAKO' pointing at a stick figure labeled 'ELON MUSK', who looks shocked. A small map of South Africa floats between them with a dotted arrow."),
    ("Then it becomes a full feud.",
     "Two stick figures labeled 'SNEAKO' and 'ELON MUSK' glaring at each other in a boxing ring, with a sign above reading 'FEUD' and lightning bolts between them."),
    ("Laura Loomer calls for his deportation too.",
     "A stick figure with long hair and a name tag 'LAURA LOOMER' holding up a protest sign with a doodle of an airplane flying away and the word 'BYE'."),
    ("Nick Fuentes, who used to be in the same online circles, starts selling \"Deport Sneako\" merch.",
     "A stick figure labeled 'NICK FUENTES' standing behind a merch table, holding up a t-shirt that reads 'DEPORT SNEAKO', with a price tag."),
    ("At the end of July, Musk goes further.",
     "A calendar page reading 'JULY', and a stick figure labeled 'ELON MUSK' climbing one step higher on a staircase."),
    ("Someone posts that Sneako needs to be deported, and Musk answers: \"He will be.\"",
     "A phone screen with a reply bubble from a stick figure with a name tag 'ELON MUSK' that reads 'HE WILL BE.' Above it, a post showing an airplane doodle flying away."),
    ("Two days later, Sneako fires back.",
     "A stick figure in a backwards cap typing angrily on a phone, with little steam puffs above its head. A sign reads '2 DAYS LATER'."),
    ("The richest man in the world keeps promising to deport him, he says, and nothing has happened.",
     "A stick figure in a backwards cap pointing and laughing at a stick figure labeled 'ELON MUSK', who holds a pile of papers labeled 'PROMISES'. An hourglass sits nearby with a sign 'STILL HERE'."),
    ("And he's right. Nothing can.",
     "A big empty cardboard box labeled 'NOTHING', and a relaxed stick figure in a backwards cap leaning on it."),
    ("But the biggest betrayal was still coming.",
     "A dark scribbled storm cloud rolling in over two stick figures holding hands, with a crack forming between their hands."),
    ("For years, Sneako and Andrew Tate were basically a package deal.",
     "Two stick figures arm in arm inside an open gift box with a bow: one in a backwards cap labeled 'SNEAKO', one bald labeled 'ANDREW TATE'."),
    ("Same audience, same streams, same enemies.",
     "Three pairs of identical circles side by side with equals signs, labeled 'AUDIENCE', 'STREAMS' and 'ENEMIES'."),
    ("Now Tate is sitting in a Miami jail cell waiting to be extradited to the UK,",
     "A bald stick figure labeled 'ANDREW TATE' sitting behind jail bars, a palm tree and a sign 'MIAMI' outside, and a dotted arrow leading to a small sign 'UK'."),
    ("and he's accusing Sneako of trying to sleep with him.",
     "A bald stick figure behind jail bars pointing with a big speech bubble reading 'ACCUSATION!'. A stick figure in a backwards cap stands outside with a shocked face and '???'."),
    ("Sneako denies it completely.",
     "A stick figure in a backwards cap holding up a giant sign that reads 'FALSE', shaking its head."),
    ("And in a long interview with Andrew Callaghan of Channel 5, he goes further than he ever has.",
     "Two stick figures sitting facing each other: one in a backwards cap labeled 'SNEAKO', and one labeled 'ANDREW CALLAGHAN' holding a microphone. A small sign reads 'CHANNEL 5'."),
    ("He says he's done with Tate, and he calls the whole manosphere a kind of militant \"feminism for men.\"",
     "A stick figure in a backwards cap crossing out a sign that reads 'MANOSPHERE' with a red marker, with a speech bubble reading 'FEMINISM FOR MEN'."),
    ("Think about that.",
     "A stick figure with a hand on its chin, thinking, with a big question mark above its head."),
    ("This is the guy who helped build that world, now calling it fake.",
     "A stick figure in a backwards cap kicking over a wobbly tower of building blocks labeled 'MANOSPHERE', with a sign reading 'FAKE'."),
    ("And just when it looked like September couldn't get weirder, a crypto casino posts an AI video of Sneako praying on top of a blackjack table.",
     "A calendar page reading 'SEPTEMBER'. Next to it, a phone screen labeled 'AI VIDEO' showing playing cards, casino chips and a coin with a 'B' on it, with a big '?!'."),
    ("Sneako, who is Muslim, says he has nothing to do with them and calls the clip disrespectful.",
     "A stick figure in a backwards cap holding up a hand in a 'stop' gesture, frowning at a phone screen labeled 'AI VIDEO', with a speech bubble reading 'NOT ME'."),
    ("The casino ends up issuing a public apology.",
     "A simple casino building doodle with flashing lights and a big banner reading 'SORRY'."),
    ("So where does that leave him?",
     "A stick figure in a backwards cap standing at a crossroads with signposts pointing in many directions, and a big question mark."),
    ("He's banned from Australia for life.",
     "A simple map of Australia with a giant padlock on it and a stick figure in a backwards cap outside, looking at it."),
    ("He's feuding with Elon Musk.",
     "Two stick figures labeled 'SNEAKO' and 'ELON MUSK' glaring at each other with jagged lightning bolts between them."),
    ("Tate, Fuentes and Loomer have all turned on him.",
     "Three stick figures labeled 'TATE', 'FUENTES' and 'LOOMER' with their backs turned, arms crossed. A lonely stick figure in a backwards cap stands behind them."),
    ("And yet somehow, he's back on YouTube, reinstated in late 2025 after nearly three years, and monetized again.",
     "A stick figure in a backwards cap walking through a door marked with a red video play button and a sign 'BACK', with green dollar signs floating around. A small sign reads 'LATE 2025'."),
    ("That's the strangest part of the Sneako story.",
     "A stick figure in a backwards cap with a confused face, and a big wobbly question mark next to it."),
    ("Every ban, every feud, every enemy he makes turns into more views.",
     "A silly machine: papers labeled 'BANS', 'FEUDS' and 'ENEMIES' go in one side, and a big pile labeled 'VIEWS' comes out the other side."),
    ("People keep saying his career is over.",
     "A crowd of stick figures pointing at a crooked gravestone that reads 'CAREER RIP'."),
    ("And then they keep clicking.",
     "Lots of stick figure hands clicking computer mice, and a view counter with an arrow going way up."),
    ("The question is how long that can last when you've burned every bridge you had.",
     "A stick figure in a backwards cap alone on a tiny island, surrounded by several bridges on fire. An hourglass sits next to it."),
]

# Beats that end a paragraph in the script (1-based), for paragraph pauses.
PARAGRAPH_ENDS = {
    3, 6, 7, 13, 18, 21, 23, 26, 29, 31, 33, 35, 36, 37, 41, 44, 46, 49, 50,
    54, 58, 59,
}

# Extra seconds where the narrator waits for the viewer to try something.
VIEWER_PAUSES = {}
